import { ArrowRight } from 'lucide-react';
import { Link } from 'react-router-dom';
import { motion, AnimatePresence } from 'motion/react';
import { useState, useEffect } from 'react';

// Each hero slide carries three formats — the browser picks the best it
// supports. Avif first (smallest), then webp, then the optimized png fallback.
// Figma-alias PNGs are 3–5 MB originals; bundling them directly would destroy LCP.
// The .webp / .avif / .opt.png siblings are generated by `npm run optimize:images`.
import hero1Avif from '../assets/356ed74642390f964957f56c9c7e341b840be530.avif';
import hero1Webp from '../assets/356ed74642390f964957f56c9c7e341b840be530.webp';
import hero1Png from '../assets/356ed74642390f964957f56c9c7e341b840be530.opt.png';
import hero2Avif from '../assets/65b443d7a3bf7b902c52cc36db6945d79d4d1f1a.avif';
import hero2Webp from '../assets/65b443d7a3bf7b902c52cc36db6945d79d4d1f1a.webp';
import hero2Png from '../assets/65b443d7a3bf7b902c52cc36db6945d79d4d1f1a.opt.png';
import hero3Avif from '../assets/50d2d3ced0e2dd397b40f90fe14b51495f2b7940.avif';
import hero3Webp from '../assets/50d2d3ced0e2dd397b40f90fe14b51495f2b7940.webp';
import hero3Png from '../assets/50d2d3ced0e2dd397b40f90fe14b51495f2b7940.opt.png';
import hero4Avif from '../assets/3c2b8795a92c4b2b191c058220691332d0c5f5de.avif';
import hero4Webp from '../assets/3c2b8795a92c4b2b191c058220691332d0c5f5de.webp';
import hero4Png from '../assets/3c2b8795a92c4b2b191c058220691332d0c5f5de.opt.png';
import hero5Avif from '../assets/a8374bfb8280ce30b87f15764a9aaf76bf6338dc.avif';
import hero5Webp from '../assets/a8374bfb8280ce30b87f15764a9aaf76bf6338dc.webp';
import hero5Png from '../assets/a8374bfb8280ce30b87f15764a9aaf76bf6338dc.opt.png';
import hero6Avif from '../assets/09ad94a08f80ddcd0bdc4edd5e14bd84ec860674.avif';
import hero6Webp from '../assets/09ad94a08f80ddcd0bdc4edd5e14bd84ec860674.webp';
import hero6Png from '../assets/09ad94a08f80ddcd0bdc4edd5e14bd84ec860674.opt.png';

interface HeroSlide {
  avif: string;
  webp: string;
  png: string;
  alt: string;
}

const heroImages: HeroSlide[] = [
  { avif: hero1Avif, webp: hero1Webp, png: hero1Png, alt: 'Rolex Day-Date with green dial' },
  { avif: hero2Avif, webp: hero2Webp, png: hero2Png, alt: 'Luxury watch collection' },
  { avif: hero3Avif, webp: hero3Webp, png: hero3Png, alt: 'Watch display showcase' },
  { avif: hero4Avif, webp: hero4Webp, png: hero4Png, alt: 'Rolex gold collection with tropical leaves' },
  { avif: hero5Avif, webp: hero5Webp, png: hero5Png, alt: 'Premium watch case collection' },
  { avif: hero6Avif, webp: hero6Webp, png: hero6Png, alt: 'Sherard W Ng with complete collection' },
];

export function Hero() {
  const [currentSlide, setCurrentSlide] = useState(0);

  useEffect(() => {
    const timer = setInterval(() => {
      setCurrentSlide((prev) => (prev + 1) % heroImages.length);
    }, 5000);
    return () => clearInterval(timer);
  }, []);

  return (
    <section className="relative h-[600px] bg-black text-white overflow-hidden">
      {/* Background carousel — <picture> gives avif/webp with PNG fallback.
          First slide gets fetchpriority=high (LCP candidate); others lazy-load. */}
      <AnimatePresence mode="wait">
        <motion.div
          key={currentSlide}
          initial={{ opacity: 0, scale: 1.05 }}
          animate={{ opacity: 1, scale: 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: 1.2, ease: 'easeInOut' }}
          className="absolute inset-0 motion-reduce:transition-none"
        >
          <picture>
            <source srcSet={heroImages[currentSlide].avif} type="image/avif" />
            <source srcSet={heroImages[currentSlide].webp} type="image/webp" />
            <img
              src={heroImages[currentSlide].png}
              alt={heroImages[currentSlide].alt}
              width={1920}
              height={1080}
              {...(currentSlide === 0
                ? { fetchPriority: 'high' as const, loading: 'eager' as const }
                : { loading: 'lazy' as const })}
              decoding="async"
              className="w-full h-full object-cover"
            />
          </picture>
          <div className="absolute inset-0 bg-gradient-to-r from-black/95 via-black/70 to-black/40" aria-hidden="true" />
        </motion.div>
      </AnimatePresence>

      <div className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-full flex items-center">
        <div className="max-w-2xl">
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3, duration: 0.8 }}
            className="text-sm tracking-widest text-[#D4AF37] mb-4 motion-reduce:transition-none"
          >
            ROLEX • PATEK PHILIPPE • AUDEMARS PIGUET • CARTIER
          </motion.p>

          <motion.h1
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.5, duration: 0.8 }}
            className="text-5xl sm:text-6xl lg:text-7xl mb-6 leading-tight font-serif motion-reduce:transition-none"
          >
            Ultra-Luxury
            <br />
            <span className="text-[#D4AF37]">Timepieces</span>
          </motion.h1>

          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.7, duration: 0.8 }}
            className="text-lg text-neutral-300 mb-8 max-w-xl motion-reduce:transition-none"
          >
            Curated by Sherard W Ng. Discover the world&apos;s most prestigious watchmakers — Rolex, Patek
            Philippe, Audemars Piguet, and Cartier. Each piece authenticated and certified.
          </motion.p>

          <Link to="/inventory">
            <motion.button
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.9, duration: 0.8 }}
              className="bg-[#D4AF37] text-black px-8 py-3 rounded-lg inline-flex items-center gap-2 hover:bg-[#F4E5B8] motion-safe:transition-colors motion-reduce:transition-none focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#D4AF37] focus-visible:ring-offset-2 focus-visible:ring-offset-black group"
            >
              <span>Explore Collection</span>
              <ArrowRight
                className="w-4 h-4 motion-safe:transition-transform motion-safe:group-hover:translate-x-1"
                aria-hidden="true"
              />
            </motion.button>
          </Link>
        </div>
      </div>

      {/* Slide Indicators */}
      <div className="absolute bottom-8 left-1/2 -translate-x-1/2 flex items-center gap-2 z-20">
        {heroImages.map((_, index) => (
          <button
            key={index}
            type="button"
            onClick={() => setCurrentSlide(index)}
            className={`motion-safe:transition-all motion-safe:duration-300 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#D4AF37] focus-visible:ring-offset-2 focus-visible:ring-offset-black ${
              index === currentSlide ? 'w-8 h-2 bg-[#D4AF37]' : 'w-2 h-2 bg-white/30 hover:bg-white/50'
            } rounded-full`}
            aria-label={`Go to slide ${index + 1} of ${heroImages.length}`}
            aria-current={index === currentSlide ? 'true' : undefined}
          />
        ))}
      </div>

      {/* Animated scroll indicator */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 1.5, duration: 1 }}
        className="absolute bottom-8 right-8 text-white hidden lg:block motion-reduce:transition-none"
        aria-hidden="true"
      >
        <div className="flex flex-col items-center gap-2">
          <span className="text-xs tracking-widest text-neutral-400">SCROLL</span>
          <motion.div
            animate={{ y: [0, 8, 0] }}
            transition={{ duration: 2, repeat: Infinity, ease: 'easeInOut' }}
            className="w-px h-12 bg-[#D4AF37] motion-reduce:animate-none"
          />
        </div>
      </motion.div>
    </section>
  );
}
