/**
 * Seed script: Insert 20 watches with accurate real-world grey market data
 * Run with: npx tsx scripts/seed-watches.ts
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const watches = [
  // ── ROLEX ──────────────────────────────────────────────────
  {
    slug: 'rolex-submariner-date-126610ln',
    brand: 'Rolex',
    model: 'Submariner Date',
    reference: '126610LN',
    year: 2023,
    caseDiameter: 41,
    caseMaterial: 'Oystersteel 904L',
    dialColor: 'Black',
    movement: 'Automatic',
    caliber: '3235',
    braceletType: 'Oyster',
    complications: ['Date'],
    condition: 'unworn',
    boxPapers: 'Full Set',
    tier: 'A',
    pricePHP: 720000,
    retailPricePHP: 625000,
    marketTrend: 'APPRECIATING',
    annualAppreciation: 5.0,
    images: [],
    category: 'Sport',
    availability: 'in_stock',
    description: 'The Rolex Submariner Date 126610LN is the definitive modern dive watch. Upgraded to 41mm with the new-generation Caliber 3235 offering 70 hours of power reserve. The black Cerachrom bezel is virtually scratch-proof and the Chromalight display provides long-lasting blue luminescence. This is the watch that every collection starts with — or returns to. Unworn, complete set with full Rolex international warranty.',
    specifications: { movement: 'Caliber 3235 Automatic', caseMaterial: 'Oystersteel 904L', diameter: '41mm', waterResistance: '300m', powerReserve: '70 hours', crystal: 'Sapphire with Cyclops' },
    featured: true,
    status: 'AVAILABLE',
  },
  {
    slug: 'rolex-submariner-date-126610lv-starbucks',
    brand: 'Rolex',
    model: 'Submariner Date',
    reference: '126610LV',
    nickname: 'Starbucks',
    year: 2023,
    caseDiameter: 41,
    caseMaterial: 'Oystersteel 904L',
    dialColor: 'Black',
    movement: 'Automatic',
    caliber: '3235',
    braceletType: 'Oyster',
    complications: ['Date'],
    condition: 'unworn',
    boxPapers: 'Full Set',
    tier: 'A',
    pricePHP: 780000,
    retailPricePHP: 650000,
    marketTrend: 'APPRECIATING',
    annualAppreciation: 6.0,
    images: [],
    category: 'Sport',
    availability: 'in_stock',
    description: 'The "Starbucks" Submariner with its green Cerachrom bezel on a black dial is the successor to the legendary "Hulk" (116610LV). The green bezel / black dial combination is more wearable than the full-green predecessor and has become one of the most sought-after Rolex sports references. Complete set, unworn condition with stickers.',
    specifications: { movement: 'Caliber 3235 Automatic', caseMaterial: 'Oystersteel 904L', diameter: '41mm', waterResistance: '300m', powerReserve: '70 hours', crystal: 'Sapphire with Cyclops' },
    featured: true,
    status: 'AVAILABLE',
  },
  {
    slug: 'rolex-gmt-master-ii-126710blro-pepsi',
    brand: 'Rolex',
    model: 'GMT-Master II',
    reference: '126710BLRO',
    nickname: 'Pepsi',
    year: 2022,
    caseDiameter: 40,
    caseMaterial: 'Oystersteel 904L',
    dialColor: 'Black',
    movement: 'Automatic',
    caliber: '3285',
    braceletType: 'Jubilee',
    complications: ['GMT', 'Date'],
    condition: 'excellent',
    boxPapers: 'Full Set',
    tier: 'A',
    pricePHP: 980000,
    retailPricePHP: 685000,
    marketTrend: 'APPRECIATING',
    annualAppreciation: 7.0,
    images: [],
    category: 'Sport',
    availability: 'in_stock',
    description: 'The Rolex GMT-Master II "Pepsi" on Jubilee bracelet is arguably the most iconic travel watch ever made. The blue-and-red Cerachrom bezel tracks a second time zone with the independently adjustable 24-hour hand. This Jubilee-bracelet configuration was the one that broke the internet at Baselworld 2018 and continues to command premiums. Excellent condition with full set.',
    specifications: { movement: 'Caliber 3285 Automatic', caseMaterial: 'Oystersteel 904L', diameter: '40mm', waterResistance: '100m', powerReserve: '70 hours', crystal: 'Sapphire with Cyclops' },
    featured: true,
    status: 'AVAILABLE',
  },
  {
    slug: 'rolex-daytona-116500ln-white',
    brand: 'Rolex',
    model: 'Cosmograph Daytona',
    reference: '116500LN',
    year: 2022,
    caseDiameter: 40,
    caseMaterial: 'Oystersteel 904L',
    dialColor: 'White',
    movement: 'Automatic',
    caliber: '4130',
    braceletType: 'Oyster',
    complications: ['Chronograph', 'Tachymeter'],
    condition: 'excellent',
    boxPapers: 'Full Set',
    tier: 'A',
    pricePHP: 1850000,
    retailPricePHP: 950000,
    marketTrend: 'APPRECIATING',
    annualAppreciation: 8.0,
    images: [],
    category: 'Sport',
    availability: 'in_stock',
    description: 'The white-dial Daytona 116500LN with Cerachrom bezel is the most coveted Rolex in the market. Retail waitlists stretch 5+ years and grey market premiums remain consistently above 90%. The white "Panda" dial configuration with black subdials and ceramic bezel is the ultimate collector piece. This watch appreciates faster than almost any other reference in production. Full set, excellent condition.',
    specifications: { movement: 'Caliber 4130 Automatic', caseMaterial: 'Oystersteel 904L', diameter: '40mm', waterResistance: '100m', powerReserve: '72 hours', crystal: 'Sapphire' },
    featured: true,
    status: 'AVAILABLE',
  },
  {
    slug: 'rolex-datejust-126334-blue',
    brand: 'Rolex',
    model: 'Datejust',
    reference: '126334',
    year: 2023,
    caseDiameter: 41,
    caseMaterial: 'Oystersteel / White Gold',
    dialColor: 'Blue',
    movement: 'Automatic',
    caliber: '3235',
    braceletType: 'Jubilee',
    complications: ['Date'],
    condition: 'unworn',
    boxPapers: 'Full Set',
    tier: 'A',
    pricePHP: 520000,
    retailPricePHP: 480000,
    marketTrend: 'STABLE',
    annualAppreciation: 0,
    images: [],
    category: 'Dress',
    availability: 'in_stock',
    description: 'The Datejust 41 in Oystersteel with white gold fluted bezel and Jubilee bracelet is the quintessential Rolex dress watch. The bright blue dial adds a modern touch to the most timeless silhouette in watchmaking. With Cal. 3235 and 70-hour power reserve, it is as technically accomplished as it is elegant. Unworn, full set.',
    specifications: { movement: 'Caliber 3235 Automatic', caseMaterial: 'Oystersteel & 18K White Gold', diameter: '41mm', waterResistance: '100m', powerReserve: '70 hours', crystal: 'Sapphire with Cyclops' },
    status: 'AVAILABLE',
  },
  {
    slug: 'rolex-day-date-228238-champagne',
    brand: 'Rolex',
    model: 'Day-Date',
    reference: '228238',
    year: 2022,
    caseDiameter: 40,
    caseMaterial: '18K Yellow Gold',
    dialColor: 'Champagne',
    movement: 'Automatic',
    caliber: '3255',
    braceletType: 'President',
    complications: ['Day', 'Date'],
    condition: 'excellent',
    boxPapers: 'Full Set',
    tier: 'B',
    pricePHP: 2200000,
    retailPricePHP: 2050000,
    marketTrend: 'APPRECIATING',
    annualAppreciation: 4.0,
    images: [],
    category: 'Luxury',
    availability: 'incoming',
    description: 'The "President" — worn by world leaders and captains of industry since 1956. The Day-Date 228238 in full 18K yellow gold with champagne dial is the original power watch. The President bracelet with concealed Crownclasp, the day display in full at 12 o\'clock, and the heft of solid gold on the wrist — nothing else communicates success quite like this. Excellent condition, complete set.',
    specifications: { movement: 'Caliber 3255 Automatic', caseMaterial: '18K Yellow Gold', diameter: '40mm', waterResistance: '100m', powerReserve: '70 hours', crystal: 'Sapphire with Cyclops' },
    status: 'AVAILABLE',
  },
  {
    slug: 'rolex-explorer-124270',
    brand: 'Rolex',
    model: 'Explorer',
    reference: '124270',
    year: 2023,
    caseDiameter: 36,
    caseMaterial: 'Oystersteel 904L',
    dialColor: 'Black',
    movement: 'Automatic',
    caliber: '3230',
    braceletType: 'Oyster',
    complications: [],
    condition: 'unworn',
    boxPapers: 'Full Set',
    tier: 'A',
    pricePHP: 450000,
    retailPricePHP: 395000,
    marketTrend: 'APPRECIATING',
    annualAppreciation: 3.0,
    images: [],
    category: 'Sport',
    availability: 'in_stock',
    description: 'The Explorer 124270 returned to its original 36mm case size — the size that conquered Everest. The 3-6-9 dial layout is the purest expression of Rolex design. No date, no complications, just a perfectly legible and incredibly robust watch for every situation. The connoisseur\'s Rolex. Unworn with complete set.',
    specifications: { movement: 'Caliber 3230 Automatic', caseMaterial: 'Oystersteel 904L', diameter: '36mm', waterResistance: '100m', powerReserve: '70 hours', crystal: 'Sapphire' },
    status: 'AVAILABLE',
  },
  {
    slug: 'rolex-yacht-master-126621-slate',
    brand: 'Rolex',
    model: 'Yacht-Master',
    reference: '126621',
    year: 2022,
    caseDiameter: 40,
    caseMaterial: 'Oystersteel / 18K Everose Gold',
    dialColor: 'Slate',
    movement: 'Automatic',
    caliber: '3235',
    braceletType: 'Oyster',
    complications: ['Date'],
    condition: 'excellent',
    boxPapers: 'Full Set',
    tier: 'A',
    pricePHP: 680000,
    retailPricePHP: 640000,
    marketTrend: 'STABLE',
    annualAppreciation: 0,
    images: [],
    category: 'Sport',
    availability: 'in_stock',
    description: 'The Yacht-Master 40 in Rolesor with Everose gold bezel and slate dial is an understated luxury sports watch. The warm rose gold tones on the bidirectional bezel complement the matte slate dial beautifully. This is the sophisticated alternative to the steel sports models — for buyers who want presence without the typical waitlist. Excellent condition, full set.',
    specifications: { movement: 'Caliber 3235 Automatic', caseMaterial: 'Oystersteel & 18K Everose Gold', diameter: '40mm', waterResistance: '100m', powerReserve: '70 hours', crystal: 'Sapphire with Cyclops' },
    status: 'AVAILABLE',
  },

  // ── PATEK PHILIPPE ─────────────────────────────────────────
  {
    slug: 'patek-philippe-nautilus-5711-1a-010',
    brand: 'Patek Philippe',
    model: 'Nautilus',
    reference: '5711/1A-010',
    year: 2020,
    caseDiameter: 40,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Blue',
    movement: 'Automatic',
    caliber: '26-330 S C',
    braceletType: 'Integrated Steel',
    complications: ['Date'],
    condition: 'excellent',
    boxPapers: 'Full Set',
    tier: 'C',
    pricePHP: 4500000,
    retailPricePHP: 1800000,
    marketTrend: 'STABLE',
    annualAppreciation: 0,
    images: [],
    category: 'Luxury',
    availability: 'in_stock',
    description: 'The Patek Philippe Nautilus 5711/1A — the watch that Thierry Stern discontinued to control demand, and the market responded by pushing prices even higher. Gerald Genta\'s 1976 porthole design became the defining luxury sports watch. The blue dial with horizontal embossing, the integrated bracelet with folding clasp, and the impossibly thin profile at just 8.3mm — this is the grail. Excellent condition with full set including extract from the archives.',
    specifications: { movement: 'Caliber 26-330 S C Automatic', caseMaterial: 'Stainless Steel', diameter: '40mm', waterResistance: '120m', powerReserve: '45 hours', crystal: 'Sapphire' },
    featured: true,
    status: 'AVAILABLE',
  },
  {
    slug: 'patek-philippe-aquanaut-5167a-001',
    brand: 'Patek Philippe',
    model: 'Aquanaut',
    reference: '5167A-001',
    year: 2021,
    caseDiameter: 40,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Black',
    movement: 'Automatic',
    caliber: '324 S C',
    braceletType: 'Composite Rubber',
    complications: ['Date'],
    condition: 'excellent',
    boxPapers: 'Full Set',
    tier: 'B',
    pricePHP: 2800000,
    retailPricePHP: 1200000,
    marketTrend: 'APPRECIATING',
    annualAppreciation: 3.0,
    images: [],
    category: 'Sport',
    availability: 'incoming',
    description: 'The Aquanaut 5167A is the "younger brother" of the Nautilus — designed for a more active lifestyle with its tropical composite strap and rounded octagonal case. The embossed black dial with Arabic numerals gives it a sportier character than the Nautilus while maintaining Patek\'s signature finishing. This is the entry point to Patek Philippe sports watches and remains significantly below the Nautilus in price, though the gap has been closing. Full set, excellent condition.',
    specifications: { movement: 'Caliber 324 S C Automatic', caseMaterial: 'Stainless Steel', diameter: '40mm', waterResistance: '120m', powerReserve: '45 hours', crystal: 'Sapphire' },
    status: 'AVAILABLE',
  },
  {
    slug: 'patek-philippe-calatrava-5227g-010',
    brand: 'Patek Philippe',
    model: 'Calatrava',
    reference: '5227G-010',
    year: 2021,
    caseDiameter: 39,
    caseMaterial: '18K White Gold',
    dialColor: 'White',
    movement: 'Automatic',
    caliber: '324 S C',
    braceletType: 'Alligator Leather',
    complications: ['Date'],
    condition: 'excellent',
    boxPapers: 'Full Set',
    tier: 'B',
    pricePHP: 1900000,
    retailPricePHP: 1850000,
    marketTrend: 'STABLE',
    annualAppreciation: 0,
    images: [],
    category: 'Dress',
    availability: 'incoming',
    description: 'The Calatrava is the soul of Patek Philippe. The 5227G-010 in white gold with its officer\'s caseback (hinged dustcover) represents classical horology at its finest. The lacquered white dial, the thin hobnail bezel pattern, and the 39mm case size are exactly right for a dress watch. This is the watch you wear to black-tie events, board meetings, and any occasion that demands quiet excellence. Full set with extract from the archives.',
    specifications: { movement: 'Caliber 324 S C Automatic', caseMaterial: '18K White Gold', diameter: '39mm', waterResistance: '30m', powerReserve: '45 hours', crystal: 'Sapphire' },
    status: 'AVAILABLE',
  },

  // ── AUDEMARS PIGUET ────────────────────────────────────────
  {
    slug: 'audemars-piguet-royal-oak-15500st',
    brand: 'Audemars Piguet',
    model: 'Royal Oak',
    reference: '15500ST',
    nickname: 'Jumbo',
    year: 2022,
    caseDiameter: 41,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Blue',
    movement: 'Automatic',
    caliber: '4302',
    braceletType: 'Integrated Steel',
    complications: ['Date'],
    condition: 'excellent',
    boxPapers: 'Full Set',
    tier: 'B',
    pricePHP: 2200000,
    retailPricePHP: 1350000,
    marketTrend: 'APPRECIATING',
    annualAppreciation: 4.0,
    images: [],
    category: 'Luxury',
    availability: 'incoming',
    description: 'The Royal Oak 15500ST with "Grande Tapisserie" blue dial is the modern evolution of Gerald Genta\'s 1972 masterpiece. The 41mm case with Cal. 4302 (70-hour power reserve) brings contemporary proportions to the octagonal legend. Every surface is hand-finished: polished and satin-brushed chamfers alternate on every edge of the case and bracelet. Nothing else in the watch world combines industrial design with haute horlogerie like the Royal Oak. Full set, excellent condition.',
    specifications: { movement: 'Caliber 4302 Automatic', caseMaterial: 'Stainless Steel', diameter: '41mm', waterResistance: '50m', powerReserve: '70 hours', crystal: 'Sapphire' },
    featured: true,
    status: 'AVAILABLE',
  },
  {
    slug: 'audemars-piguet-royal-oak-chrono-26331st',
    brand: 'Audemars Piguet',
    model: 'Royal Oak Chronograph',
    reference: '26331ST',
    year: 2021,
    caseDiameter: 41,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Blue',
    movement: 'Automatic',
    caliber: '2385',
    braceletType: 'Integrated Steel',
    complications: ['Chronograph', 'Date'],
    condition: 'excellent',
    boxPapers: 'Full Set',
    tier: 'B',
    pricePHP: 2800000,
    retailPricePHP: 1650000,
    marketTrend: 'APPRECIATING',
    annualAppreciation: 5.0,
    images: [],
    category: 'Sport',
    availability: 'incoming',
    description: 'The Royal Oak Chronograph 26331ST adds a column-wheel flyback chronograph to the iconic octagonal case. The blue dial with "Grande Tapisserie" pattern houses two subdials at 6 and 12, with a date window at 3. The additional complication adds thickness and presence without losing the Royal Oak\'s distinctive profile. This is the piece for collectors who want the Royal Oak DNA with more functionality. Full set.',
    specifications: { movement: 'Caliber 2385 Automatic', caseMaterial: 'Stainless Steel', diameter: '41mm', waterResistance: '50m', powerReserve: '40 hours', crystal: 'Sapphire' },
    status: 'AVAILABLE',
  },
  {
    slug: 'audemars-piguet-royal-oak-offshore-26470st',
    brand: 'Audemars Piguet',
    model: 'Royal Oak Offshore',
    reference: '26470ST',
    year: 2021,
    caseDiameter: 42,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Black',
    movement: 'Automatic',
    caliber: '3126/3840',
    braceletType: 'Rubber',
    complications: ['Chronograph', 'Date'],
    condition: 'excellent',
    boxPapers: 'Full Set',
    tier: 'A',
    pricePHP: 1600000,
    retailPricePHP: 1500000,
    marketTrend: 'STABLE',
    annualAppreciation: 0,
    images: [],
    category: 'Sport',
    availability: 'in_stock',
    description: 'The Royal Oak Offshore — the "Beast" that redefined AP in 1993. The 26470ST chronograph in steel with rubber strap is the most wearable expression of the Offshore line. At 42mm with integrated rubber strap and chronograph pushers, it carries the aggressive DNA of the original while being practical enough for daily wear. Full set, excellent condition.',
    specifications: { movement: 'Caliber 3126/3840 Automatic', caseMaterial: 'Stainless Steel', diameter: '42mm', waterResistance: '100m', powerReserve: '50 hours', crystal: 'Sapphire' },
    status: 'AVAILABLE',
  },

  // ── CARTIER ────────────────────────────────────────────────
  {
    slug: 'cartier-santos-wssa0018',
    brand: 'Cartier',
    model: 'Santos de Cartier',
    reference: 'WSSA0018',
    year: 2023,
    caseDiameter: 39.8,
    caseMaterial: 'Stainless Steel',
    dialColor: 'White',
    movement: 'Automatic',
    caliber: '1847 MC',
    braceletType: 'Steel + Leather (QuickSwitch)',
    complications: ['Date'],
    condition: 'unworn',
    boxPapers: 'Full Set',
    tier: 'A',
    pricePHP: 380000,
    retailPricePHP: 370000,
    marketTrend: 'STABLE',
    annualAppreciation: 0,
    images: [],
    category: 'Dress',
    availability: 'in_stock',
    description: 'The Santos de Cartier is the original pilot\'s watch — designed by Louis Cartier for aviator Alberto Santos-Dumont in 1904. The modern WSSA0018 in large steel keeps the iconic square case with exposed screws and adds Cartier\'s QuickSwitch system for swapping between steel bracelet and leather strap without tools. The SmartLink system also allows bracelet sizing without a jeweler. A masterclass in updating a classic. Unworn, complete set.',
    specifications: { movement: 'Caliber 1847 MC Automatic', caseMaterial: 'Stainless Steel', diameter: '39.8mm', waterResistance: '100m', powerReserve: '42 hours', crystal: 'Sapphire' },
    status: 'AVAILABLE',
  },
  {
    slug: 'cartier-tank-francaise-wsta0065',
    brand: 'Cartier',
    model: 'Tank Francaise',
    reference: 'WSTA0065',
    year: 2023,
    caseDiameter: 36.7,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Silver',
    movement: 'Quartz',
    caliber: null,
    braceletType: 'Steel',
    complications: [],
    condition: 'unworn',
    boxPapers: 'Full Set',
    tier: 'A',
    pricePHP: 320000,
    retailPricePHP: 285000,
    marketTrend: 'APPRECIATING',
    annualAppreciation: 3.0,
    images: [],
    category: 'Dress',
    availability: 'in_stock',
    description: 'The redesigned Tank Francaise (2023) has been a sensation. The softened curves, the integrated bracelet with new link geometry, and the refined proportions make this the most desirable Tank in years. The medium size at 36.7mm × 32mm wears perfectly on any wrist. The guilloched silver dial with blued-steel sword hands is pure Cartier elegance. Unworn with complete set. Strong demand — Cartier has been allocating this reference similarly to steel Rolex sports.',
    specifications: { movement: 'Quartz', caseMaterial: 'Stainless Steel', diameter: '36.7 x 32mm', waterResistance: '30m', crystal: 'Sapphire' },
    status: 'AVAILABLE',
  },

  // ── OMEGA ──────────────────────────────────────────────────
  {
    slug: 'omega-speedmaster-professional-310-30-42-50-01-001',
    brand: 'Omega',
    model: 'Speedmaster Professional Moonwatch',
    reference: '310.30.42.50.01.001',
    year: 2023,
    caseDiameter: 42,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Black',
    movement: 'Manual',
    caliber: '3861',
    braceletType: 'Steel',
    complications: ['Chronograph', 'Tachymeter'],
    condition: 'unworn',
    boxPapers: 'Full Set',
    tier: 'A',
    pricePHP: 350000,
    retailPricePHP: 330000,
    marketTrend: 'APPRECIATING',
    annualAppreciation: 4.0,
    images: [],
    category: 'Sport',
    availability: 'in_stock',
    description: 'The Moonwatch. First watch worn on the lunar surface. The current reference with Co-Axial Master Chronometer Caliber 3861 retains the hand-wound character of the original while adding METAS certification and 50-hour power reserve. The hesalite crystal, stepped dial, and asymmetric case maintain the silhouette that NASA approved for spaceflight. This is not just a watch — it\'s a piece of human achievement on your wrist. Unworn, complete set with NASA-style presentation box.',
    specifications: { movement: 'Caliber 3861 Manual Wind', caseMaterial: 'Stainless Steel', diameter: '42mm', waterResistance: '50m', powerReserve: '50 hours', crystal: 'Hesalite' },
    status: 'AVAILABLE',
  },
  {
    slug: 'omega-seamaster-300m-210-30-42-20-01-001',
    brand: 'Omega',
    model: 'Seamaster 300M',
    reference: '210.30.42.20.01.001',
    year: 2023,
    caseDiameter: 42,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Black',
    movement: 'Automatic',
    caliber: '8800',
    braceletType: 'Steel',
    complications: ['Date'],
    condition: 'unworn',
    boxPapers: 'Full Set',
    tier: 'A',
    pricePHP: 280000,
    retailPricePHP: 268000,
    marketTrend: 'STABLE',
    annualAppreciation: 0,
    images: [],
    category: 'Sport',
    availability: 'in_stock',
    description: 'The Seamaster 300M is the Bond watch — worn by Daniel Craig through five films. The ceramic bezel with enamel-filled diving scale, laser-engraved wave dial, and helium escape valve at 10 o\'clock give it professional dive credentials. The Co-Axial Master Chronometer Cal. 8800 is resistant to magnetic fields up to 15,000 gauss. The best value in luxury dive watches. Unworn, complete set.',
    specifications: { movement: 'Caliber 8800 Co-Axial Automatic', caseMaterial: 'Stainless Steel', diameter: '42mm', waterResistance: '300m', powerReserve: '55 hours', crystal: 'Sapphire' },
    status: 'AVAILABLE',
  },

  // ── TUDOR ──────────────────────────────────────────────────
  {
    slug: 'tudor-black-bay-58-m79030n',
    brand: 'Tudor',
    model: 'Black Bay Fifty-Eight',
    reference: 'M79030N',
    year: 2023,
    caseDiameter: 39,
    caseMaterial: 'Stainless Steel',
    dialColor: 'Black',
    movement: 'Automatic',
    caliber: 'MT5402',
    braceletType: 'Steel',
    complications: [],
    condition: 'unworn',
    boxPapers: 'Full Set',
    tier: 'A',
    pricePHP: 195000,
    retailPricePHP: 180000,
    marketTrend: 'APPRECIATING',
    annualAppreciation: 5.0,
    images: [],
    category: 'Sport',
    availability: 'in_stock',
    description: 'The Black Bay Fifty-Eight is Tudor\'s most popular watch and for good reason. The 39mm case size (inspired by Tudor\'s 1958 reference 7924) is perfect on the wrist — not too big, not too small. The in-house MT5402 chronometer movement with 70-hour power reserve is manufactured to Rolex standards. This is the best value proposition in the dive watch segment. Unworn, complete set.',
    specifications: { movement: 'Caliber MT5402 Automatic', caseMaterial: 'Stainless Steel', diameter: '39mm', waterResistance: '200m', powerReserve: '70 hours', crystal: 'Sapphire' },
    status: 'AVAILABLE',
  },
  {
    slug: 'tudor-pelagos-m25600tn',
    brand: 'Tudor',
    model: 'Pelagos',
    reference: 'M25600TN',
    year: 2022,
    caseDiameter: 42,
    caseMaterial: 'Titanium',
    dialColor: 'Black',
    movement: 'Automatic',
    caliber: 'MT5612',
    braceletType: 'Titanium',
    complications: ['Date'],
    condition: 'excellent',
    boxPapers: 'Full Set',
    tier: 'A',
    pricePHP: 220000,
    retailPricePHP: 210000,
    marketTrend: 'STABLE',
    annualAppreciation: 0,
    images: [],
    category: 'Sport',
    availability: 'in_stock',
    description: 'The Tudor Pelagos is a serious dive watch in lightweight titanium rated to 500m. The self-adjusting clasp (spring mechanism that compensates for wetsuit compression), helium escape valve, and ceramic bezel make it one of the most capable tool watches under ₱250k. The in-house MT5612 provides 70 hours of power reserve. Full titanium construction keeps the weight remarkably light despite the 42mm case. Excellent condition, complete set with both titanium bracelet and rubber strap.',
    specifications: { movement: 'Caliber MT5612 Automatic', caseMaterial: 'Titanium', diameter: '42mm', waterResistance: '500m', powerReserve: '70 hours', crystal: 'Sapphire' },
    status: 'AVAILABLE',
  },
];

async function main() {
  console.log('Seeding 20 watches...\n');

  let created = 0;
  let skipped = 0;

  for (const w of watches) {
    const existing = await prisma.watch.findUnique({ where: { slug: w.slug } });
    if (existing) {
      console.log(`  Skipping: ${w.brand} ${w.model} (${w.reference}) — already exists`);
      skipped++;
      continue;
    }

    await prisma.watch.create({
      data: {
        slug: w.slug,
        brand: w.brand,
        model: w.model,
        reference: w.reference,
        nickname: w.nickname || null,
        year: w.year || null,
        caseDiameter: w.caseDiameter || null,
        caseMaterial: w.caseMaterial || null,
        dialColor: w.dialColor || null,
        movement: w.movement || null,
        caliber: w.caliber || null,
        braceletType: w.braceletType || null,
        complications: w.complications || [],
        condition: w.condition,
        boxPapers: w.boxPapers,
        tier: w.tier,
        pricePHP: w.pricePHP,
        retailPricePHP: w.retailPricePHP || null,
        marketTrend: w.marketTrend || null,
        annualAppreciation: w.annualAppreciation || null,
        images: w.images || [],
        video: null,
        category: w.category,
        availability: w.availability,
        description: w.description,
        specifications: w.specifications as any,
        featured: w.featured || false,
        status: w.status || 'AVAILABLE',
      },
    });

    console.log(`  Created: ${w.brand} ${w.model} ${w.reference} — ₱${w.pricePHP.toLocaleString()}`);
    created++;
  }

  console.log(`\nSeed complete! Created: ${created}, Skipped: ${skipped}`);
}

main()
  .catch((e) => {
    console.error('Seed failed:', e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
